/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 14-kvì-2016 20:49:35 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `syslog` CASCADE
;

/* Create Tables */

CREATE TABLE `syslog`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`logDateTime` DATETIME 	 NULL,
	`userId` INT 	 NULL,
	`ip` VARCHAR(15) 	 NULL,
	`presenter` VARCHAR(50) 	 NULL,
	`function` VARCHAR(50) 	 NULL,
	`level` VARCHAR(50) 	 NULL,
	`message` TEXT 	 NULL,
	CONSTRAINT `PK_syslog` PRIMARY KEY (`id` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `syslog` 
 ADD INDEX `IDX_userId` (`userId` ASC)
;

ALTER TABLE `syslog` 
 ADD INDEX `IDX_logDateTime` (`logDateTime` ASC)
;

ALTER TABLE `syslog` 
 ADD INDEX `IDX_ip` (`ip` ASC)
;

ALTER TABLE `syslog` 
 ADD INDEX `IDX_level` (`level` ASC)
;

ALTER TABLE `syslog` 
 ADD INDEX `IDX_presenter` (`presenter` ASC)
;

ALTER TABLE `syslog` 
 ADD INDEX `IDX_function` (`function` ASC)
;

SET FOREIGN_KEY_CHECKS=1 
;
